### ISSUE TITLE
consultation for function in code

### ISSUE THREAD

**Issue by ouyangzhenxing** [matthewgiarra/piv-image-generation#2]
There is no gaussianWindowFilter which is loaded in test_generation_fullImage.m and others. 
Could you provide a ZIP  package which could be  used  directly? Thank you very much!

**Comment by matthewgiarra** [comment]
I just pushed that code and a supporting code to this repository. Re-open this if it's not what you need.

**Comment by ouyangzhenxing** [comment]
Thank you very much!
